// The author(s) disclaim copyright to this source-code.
// Can be licensed under MIT (in case the public domain is not recognized).
// More information can be found in the LICENSE file.

#ifndef _FOUNDATION_DETECT_SUPPORTED_STANDARDS_H_
#define _FOUNDATION_DETECT_SUPPORTED_STANDARDS_H_

// Tries to detect support for the C++11 standard based on compiler version.

#include <foundation/detect/compiler.h>

#if defined(FOUNDATION_COMPILER_MSVC)
  #if (FOUNDATION_COMPILER_MSVC >= MICROSOFT_VISUAL_STUDIO_2010)
    #define FOUNDATION_COMPILER_SUPPORTS_RVALUES 1
    #define FOUNDATION_COMPILER_SUPPORTS_VARADIC_TEMPLATES 0
    #define FOUNDATION_COMPILER_SUPPORTS_INITIALIZER_LISTS 0
    #define FOUNDATION_COMPILER_SUPPORTS_STATIC_ASSERTIONS 1
    #define FOUNDATION_COMPILER_SUPPORTS_AUTO 1
    #define FOUNDATION_COMPILER_SUPPORTS_LAMBDAS_AND_CLOSURES 1
    #define FOUNDATION_COMPILER_SUPPORTS_DECLTYPE 1
    // #define FOUNDATION_COMPILER_SUPPORTS_RIGHT_ANGLE_BRACKETS 1
    #define FOUNDATION_COMPILER_SUPPORTS_DEFAULT_TEMPLATE_ARGUMENTS_FOR_FUNCTIONS 0
    #define FOUNDATION_COMPILER_SUPPORTS_ALIAS_TEMPLATES 0
    #define FOUNDATION_COMPILER_SUPPORTS_EXTERN_TEMPLATES 1
    #define FOUNDATION_COMPILER_SUPPORTS_NULLPTR 1
    #define FOUNDATION_COMPILER_SUPPORTS_STRONGLY_TYPED_ENUMS 1
    #define FOUNDATION_COMPILER_SUPPORTS_ALIGNMENT 0
    #define FOUNDATION_COMPILER_SUPPORTS_DELEGATING_CONSTRUCTORS 0
    #define FOUNDATION_COMPILER_SUPPORTS_INHERITING_CONSTRUCTORS 0
    #define FOUNDATION_COMPILER_SUPPORTS_UNRESTRICTED_UNIONS 0
  #elif (FOUNDATION_COMPILER_MSVC <= MICROSOFT_VISUAL_STUDIO_2008)
    #define FOUNDATION_COMPILER_SUPPORTS_RVALUES 0
    #define FOUNDATION_COMPILER_SUPPORTS_VARADIC_TEMPLATES 0
    #define FOUNDATION_COMPILER_SUPPORTS_INITIALIZER_LISTS 0
    #define FOUNDATION_COMPILER_SUPPORTS_STATIC_ASSERTIONS 0
    #define FOUNDATION_COMPILER_SUPPORTS_AUTO 0
    #define FOUNDATION_COMPILER_SUPPORTS_LAMBDAS_AND_CLOSURES 0
    #define FOUNDATION_COMPILER_SUPPORTS_DECLTYPE 0
    // #define FOUNDATION_COMPILER_SUPPORTS_RIGHT_ANGLE_BRACKETS 0
    #define FOUNDATION_COMPILER_SUPPORTS_DEFAULT_TEMPLATE_ARGUMENTS_FOR_FUNCTIONS 0
    #define FOUNDATION_COMPILER_SUPPORTS_ALIAS_TEMPLATES 0
    #define FOUNDATION_COMPILER_SUPPORTS_EXTERN_TEMPLATES 0
    #define FOUNDATION_COMPILER_SUPPORTS_NULLPTR 0
    #define FOUNDATION_COMPILER_SUPPORTS_STRONGLY_TYPED_ENUMS 0
    #define FOUNDATION_COMPILER_SUPPORTS_ALIGNMENT 0
    #define FOUNDATION_COMPILER_SUPPORTS_DELEGATING_CONSTRUCTORS 0
    #define FOUNDATION_COMPILER_SUPPORTS_INHERITING_CONSTRUCTORS 0
    #define FOUNDATION_COMPILER_SUPPORTS_UNRESTRICTED_UNIONS 0
  #endif
#elif defined(FOUNDATION_COMPILER_CLANG)
  #define FOUNDATION_COMPILER_SUPPORTS_RVALUES __has_feature(cxx_rvalue_references);
  #define FOUNDATION_COMPILER_SUPPORTS_VARADIC_TEMPLATES __has_feature(cxx_variadic_templates);
  #define FOUNDATION_COMPILER_SUPPORTS_INITIALIZER_LISTS 0
  #define FOUNDATION_COMPILER_SUPPORTS_STATIC_ASSERTIONS __has_feature(cxx_static_assert);
  #define FOUNDATION_COMPILER_SUPPORTS_AUTO 1
  #define FOUNDATION_COMPILER_SUPPORTS_LAMBDAS_AND_CLOSURES __has_feature(cxx_lambdas);
  #define FOUNDATION_COMPILER_SUPPORTS_DECLTYPE __has_feature(cxx_decltype);
  // #define FOUNDATION_COMPILER_SUPPORTS_RIGHT_ANGLE_BRACKETS 1
  #define FOUNDATION_COMPILER_SUPPORTS_DEFAULT_TEMPLATE_ARGUMENTS_FOR_FUNCTIONS __has_feature(cxx_default_function_template_args);
  #define FOUNDATION_COMPILER_SUPPORTS_ALIAS_TEMPLATES __has_feature(cxx_alias_templates);
  #define FOUNDATION_COMPILER_SUPPORTS_EXTERN_TEMPLATES 1
  #define FOUNDATION_COMPILER_SUPPORTS_NULLPTR __has_feature(cxx_nullptr);
  #define FOUNDATION_COMPILER_SUPPORTS_STRONGLY_TYPED_ENUMS __has_feature(cxx_strong_enums);
  #define FOUNDATION_COMPILER_SUPPORTS_ALIGNMENT 1
  #define FOUNDATION_COMPILER_SUPPORTS_DELEGATING_CONSTRUCTORS __has_feature(cxx_delegating_constructors);
  #define FOUNDATION_COMPILER_SUPPORTS_INHERITING_CONSTRUCTORS __has_feature(cxx_inheriting_constructors);
  #define FOUNDATION_COMPILER_SUPPORTS_UNRESTRICTED_UNIONS __has_feature(cxx_unrestricted_unions);
#elif defined(FOUNDATION_COMPILER_GCC)
  #if (FOUNDATION_COMPILER_GCC >= 460)
    #define FOUNDATION_COMPILER_SUPPORTS_RVALUES 1
    #define FOUNDATION_COMPILER_SUPPORTS_VARADIC_TEMPLATES 1
    #define FOUNDATION_COMPILER_SUPPORTS_INITIALIZER_LISTS 1
    #define FOUNDATION_COMPILER_SUPPORTS_STATIC_ASSERTIONS 1
    #define FOUNDATION_COMPILER_SUPPORTS_AUTO 1
    #define FOUNDATION_COMPILER_SUPPORTS_LAMBDAS_AND_CLOSURES 1
    #define FOUNDATION_COMPILER_SUPPORTS_DECLTYPE 1
    // #define FOUNDATION_COMPILER_SUPPORTS_RIGHT_ANGLE_BRACKETS 1
    #define FOUNDATION_COMPILER_SUPPORTS_DEFAULT_TEMPLATE_ARGUMENTS_FOR_FUNCTIONS 1
    #define FOUNDATION_COMPILER_SUPPORTS_ALIAS_TEMPLATES 1
    #define FOUNDATION_COMPILER_SUPPORTS_EXTERN_TEMPLATES 1
    #define FOUNDATION_COMPILER_SUPPORTS_NULLPTR 1
    #define FOUNDATION_COMPILER_SUPPORTS_STRONGLY_TYPED_ENUMS 1
    #define FOUNDATION_COMPILER_SUPPORTS_ALIGNMENT 1
    #define FOUNDATION_COMPILER_SUPPORTS_DELEGATING_CONSTRUCTORS 1
    #define FOUNDATION_COMPILER_SUPPORTS_INHERITING_CONSTRUCTORS 1
    #define FOUNDATION_COMPILER_SUPPORTS_UNRESTRICTED_UNIONS 1
  #elif (FOUNDATION_COMPILER_GCC >= 460)
    #define FOUNDATION_COMPILER_SUPPORTS_RVALUES 1
    #define FOUNDATION_COMPILER_SUPPORTS_VARADIC_TEMPLATES 1
    #define FOUNDATION_COMPILER_SUPPORTS_INITIALIZER_LISTS 1
    #define FOUNDATION_COMPILER_SUPPORTS_STATIC_ASSERTIONS 1
    #define FOUNDATION_COMPILER_SUPPORTS_AUTO 1
    #define FOUNDATION_COMPILER_SUPPORTS_LAMBDAS_AND_CLOSURES 1
    #define FOUNDATION_COMPILER_SUPPORTS_DECLTYPE 1
    // #define FOUNDATION_COMPILER_SUPPORTS_RIGHT_ANGLE_BRACKETS 1
    #define FOUNDATION_COMPILER_SUPPORTS_DEFAULT_TEMPLATE_ARGUMENTS_FOR_FUNCTIONS 1
    #define FOUNDATION_COMPILER_SUPPORTS_ALIAS_TEMPLATES 1
    #define FOUNDATION_COMPILER_SUPPORTS_EXTERN_TEMPLATES 1
    #define FOUNDATION_COMPILER_SUPPORTS_NULLPTR 1
    #define FOUNDATION_COMPILER_SUPPORTS_STRONGLY_TYPED_ENUMS 1
    #define FOUNDATION_COMPILER_SUPPORTS_ALIGNMENT 0
    #define FOUNDATION_COMPILER_SUPPORTS_DELEGATING_CONSTRUCTORS 1
    #define FOUNDATION_COMPILER_SUPPORTS_INHERITING_CONSTRUCTORS 0
    #define FOUNDATION_COMPILER_SUPPORTS_UNRESTRICTED_UNIONS 1
  #elif (FOUNDATION_COMPILER_GCC >= 460)
    #define FOUNDATION_COMPILER_SUPPORTS_RVALUES 1
    #define FOUNDATION_COMPILER_SUPPORTS_VARADIC_TEMPLATES 1
    #define FOUNDATION_COMPILER_SUPPORTS_INITIALIZER_LISTS 1
    #define FOUNDATION_COMPILER_SUPPORTS_STATIC_ASSERTIONS 1
    #define FOUNDATION_COMPILER_SUPPORTS_AUTO 1
    #define FOUNDATION_COMPILER_SUPPORTS_LAMBDAS_AND_CLOSURES 1
    #define FOUNDATION_COMPILER_SUPPORTS_DECLTYPE 1
    // #define FOUNDATION_COMPILER_SUPPORTS_RIGHT_ANGLE_BRACKETS 1
    #define FOUNDATION_COMPILER_SUPPORTS_DEFAULT_TEMPLATE_ARGUMENTS_FOR_FUNCTIONS 1
    #define FOUNDATION_COMPILER_SUPPORTS_ALIAS_TEMPLATES 0
    #define FOUNDATION_COMPILER_SUPPORTS_EXTERN_TEMPLATES 1
    #define FOUNDATION_COMPILER_SUPPORTS_NULLPTR 1
    #define FOUNDATION_COMPILER_SUPPORTS_STRONGLY_TYPED_ENUMS 1
    #define FOUNDATION_COMPILER_SUPPORTS_ALIGNMENT 0
    #define FOUNDATION_COMPILER_SUPPORTS_DELEGATING_CONSTRUCTORS 0
    #define FOUNDATION_COMPILER_SUPPORTS_INHERITING_CONSTRUCTORS 0
    #define FOUNDATION_COMPILER_SUPPORTS_UNRESTRICTED_UNIONS 1
  #elif (FOUNDATION_COMPILER_GCC >= 450)
    #define FOUNDATION_COMPILER_SUPPORTS_RVALUES 1
    #define FOUNDATION_COMPILER_SUPPORTS_VARADIC_TEMPLATES 1
    #define FOUNDATION_COMPILER_SUPPORTS_INITIALIZER_LISTS 1
    #define FOUNDATION_COMPILER_SUPPORTS_STATIC_ASSERTIONS 1
    #define FOUNDATION_COMPILER_SUPPORTS_AUTO 1
    #define FOUNDATION_COMPILER_SUPPORTS_LAMBDAS_AND_CLOSURES 1
    #define FOUNDATION_COMPILER_SUPPORTS_DECLTYPE 1
    // #define FOUNDATION_COMPILER_SUPPORTS_RIGHT_ANGLE_BRACKETS 1
    #define FOUNDATION_COMPILER_SUPPORTS_DEFAULT_TEMPLATE_ARGUMENTS_FOR_FUNCTIONS 1
    #define FOUNDATION_COMPILER_SUPPORTS_ALIAS_TEMPLATES 0
    #define FOUNDATION_COMPILER_SUPPORTS_EXTERN_TEMPLATES 1
    #define FOUNDATION_COMPILER_SUPPORTS_NULLPTR 0
    #define FOUNDATION_COMPILER_SUPPORTS_STRONGLY_TYPED_ENUMS 1
    #define FOUNDATION_COMPILER_SUPPORTS_ALIGNMENT 0
    #define FOUNDATION_COMPILER_SUPPORTS_DELEGATING_CONSTRUCTORS 0
    #define FOUNDATION_COMPILER_SUPPORTS_INHERITING_CONSTRUCTORS 0
    #define FOUNDATION_COMPILER_SUPPORTS_UNRESTRICTED_UNIONS 0
  #elif (FOUNDATION_COMPILER_GCC >= 440)
    #define FOUNDATION_COMPILER_SUPPORTS_RVALUES 1
    #define FOUNDATION_COMPILER_SUPPORTS_VARADIC_TEMPLATES 1
    #define FOUNDATION_COMPILER_SUPPORTS_INITIALIZER_LISTS 1
    #define FOUNDATION_COMPILER_SUPPORTS_STATIC_ASSERTIONS 1
    #define FOUNDATION_COMPILER_SUPPORTS_AUTO 1
    #define FOUNDATION_COMPILER_SUPPORTS_LAMBDAS_AND_CLOSURES 0
    #define FOUNDATION_COMPILER_SUPPORTS_DECLTYPE 1
    // #define FOUNDATION_COMPILER_SUPPORTS_RIGHT_ANGLE_BRACKETS 1
    #define FOUNDATION_COMPILER_SUPPORTS_DEFAULT_TEMPLATE_ARGUMENTS_FOR_FUNCTIONS 1
    #define FOUNDATION_COMPILER_SUPPORTS_ALIAS_TEMPLATES 0
    #define FOUNDATION_COMPILER_SUPPORTS_EXTERN_TEMPLATES 1
    #define FOUNDATION_COMPILER_SUPPORTS_NULLPTR 0
    #define FOUNDATION_COMPILER_SUPPORTS_STRONGLY_TYPED_ENUMS 1
    #define FOUNDATION_COMPILER_SUPPORTS_ALIGNMENT 0
    #define FOUNDATION_COMPILER_SUPPORTS_DELEGATING_CONSTRUCTORS 0
    #define FOUNDATION_COMPILER_SUPPORTS_INHERITING_CONSTRUCTORS 0
    #define FOUNDATION_COMPILER_SUPPORTS_UNRESTRICTED_UNIONS 0
  #elif (FOUNDATION_COMPILER_GCC >= 430)
    #define FOUNDATION_COMPILER_SUPPORTS_RVALUES 1
    #define FOUNDATION_COMPILER_SUPPORTS_VARADIC_TEMPLATES 1
    #define FOUNDATION_COMPILER_SUPPORTS_INITIALIZER_LISTS 0
    #define FOUNDATION_COMPILER_SUPPORTS_STATIC_ASSERTIONS 1
    #define FOUNDATION_COMPILER_SUPPORTS_AUTO 0
    #define FOUNDATION_COMPILER_SUPPORTS_LAMBDAS_AND_CLOSURES 0
    #define FOUNDATION_COMPILER_SUPPORTS_DECLTYPE 1
    // #define FOUNDATION_COMPILER_SUPPORTS_RIGHT_ANGLE_BRACKETS 1
    #define FOUNDATION_COMPILER_SUPPORTS_DEFAULT_TEMPLATE_ARGUMENTS_FOR_FUNCTIONS 1
    #define FOUNDATION_COMPILER_SUPPORTS_ALIAS_TEMPLATES 0
    #define FOUNDATION_COMPILER_SUPPORTS_EXTERN_TEMPLATES 1
    #define FOUNDATION_COMPILER_SUPPORTS_NULLPTR 0
    #define FOUNDATION_COMPILER_SUPPORTS_STRONGLY_TYPED_ENUMS 0
    #define FOUNDATION_COMPILER_SUPPORTS_ALIGNMENT 0
    #define FOUNDATION_COMPILER_SUPPORTS_DELEGATING_CONSTRUCTORS 0
    #define FOUNDATION_COMPILER_SUPPORTS_INHERITING_CONSTRUCTORS 0
    #define FOUNDATION_COMPILER_SUPPORTS_UNRESTRICTED_UNIONS 0
  #endif
#elif defined(FOUNDATION_COMPILER_ICC)
  #if (FOUNDATION_COMPILER_ICC >= 1300)
    #define FOUNDATION_COMPILER_SUPPORTS_RVALUES 1
    #define FOUNDATION_COMPILER_SUPPORTS_VARADIC_TEMPLATES 1
    #define FOUNDATION_COMPILER_SUPPORTS_INITIALIZER_LISTS 1
    #define FOUNDATION_COMPILER_SUPPORTS_STATIC_ASSERTIONS 1
    #define FOUNDATION_COMPILER_SUPPORTS_AUTO 1
    #define FOUNDATION_COMPILER_SUPPORTS_LAMBDAS_AND_CLOSURES 1
    #define FOUNDATION_COMPILER_SUPPORTS_DECLTYPE 1
    // #define FOUNDATION_COMPILER_SUPPORTS_RIGHT_ANGLE_BRACKETS 1
    #define FOUNDATION_COMPILER_SUPPORTS_DEFAULT_TEMPLATE_ARGUMENTS_FOR_FUNCTIONS 1
    #define FOUNDATION_COMPILER_SUPPORTS_ALIAS_TEMPLATES 1
    #define FOUNDATION_COMPILER_SUPPORTS_EXTERN_TEMPLATES 1
    #define FOUNDATION_COMPILER_SUPPORTS_NULLPTR 1
    #define FOUNDATION_COMPILER_SUPPORTS_STRONGLY_TYPED_ENUMS 1
    #define FOUNDATION_COMPILER_SUPPORTS_ALIGNMENT 0
    #define FOUNDATION_COMPILER_SUPPORTS_DELEGATING_CONSTRUCTORS 0
    #define FOUNDATION_COMPILER_SUPPORTS_INHERITING_CONSTRUCTORS 0
    #define FOUNDATION_COMPILER_SUPPORTS_UNRESTRICTED_UNIONS 0
  #elif (FOUNDATION_COMPILER_ICC >= 1210)
    #define FOUNDATION_COMPILER_SUPPORTS_RVALUES 1
    #define FOUNDATION_COMPILER_SUPPORTS_VARADIC_TEMPLATES 1
    #define FOUNDATION_COMPILER_SUPPORTS_INITIALIZER_LISTS 0
    #define FOUNDATION_COMPILER_SUPPORTS_STATIC_ASSERTIONS 1
    #define FOUNDATION_COMPILER_SUPPORTS_AUTO 1
    #define FOUNDATION_COMPILER_SUPPORTS_LAMBDAS_AND_CLOSURES 1
    #define FOUNDATION_COMPILER_SUPPORTS_DECLTYPE 1
    // #define FOUNDATION_COMPILER_SUPPORTS_RIGHT_ANGLE_BRACKETS 1
    #define FOUNDATION_COMPILER_SUPPORTS_DEFAULT_TEMPLATE_ARGUMENTS_FOR_FUNCTIONS 1
    #define FOUNDATION_COMPILER_SUPPORTS_ALIAS_TEMPLATES 1
    #define FOUNDATION_COMPILER_SUPPORTS_EXTERN_TEMPLATES 1
    #define FOUNDATION_COMPILER_SUPPORTS_NULLPTR 1
    #define FOUNDATION_COMPILER_SUPPORTS_STRONGLY_TYPED_ENUMS 1
    #define FOUNDATION_COMPILER_SUPPORTS_ALIGNMENT 0
    #define FOUNDATION_COMPILER_SUPPORTS_DELEGATING_CONSTRUCTORS 0
    #define FOUNDATION_COMPILER_SUPPORTS_INHERITING_CONSTRUCTORS 0
    #define FOUNDATION_COMPILER_SUPPORTS_UNRESTRICTED_UNIONS 0
  #elif (FOUNDATION_COMPILER_ICC >= 1200)
    #define FOUNDATION_COMPILER_SUPPORTS_RVALUES 1
    #define FOUNDATION_COMPILER_SUPPORTS_VARADIC_TEMPLATES 0
    #define FOUNDATION_COMPILER_SUPPORTS_INITIALIZER_LISTS 0
    #define FOUNDATION_COMPILER_SUPPORTS_STATIC_ASSERTIONS 1
    #define FOUNDATION_COMPILER_SUPPORTS_AUTO 1
    #define FOUNDATION_COMPILER_SUPPORTS_LAMBDAS_AND_CLOSURES 1
    #define FOUNDATION_COMPILER_SUPPORTS_DECLTYPE 1
    // #define FOUNDATION_COMPILER_SUPPORTS_RIGHT_ANGLE_BRACKETS 1
    #define FOUNDATION_COMPILER_SUPPORTS_DEFAULT_TEMPLATE_ARGUMENTS_FOR_FUNCTIONS 0
    #define FOUNDATION_COMPILER_SUPPORTS_ALIAS_TEMPLATES 0
    #define FOUNDATION_COMPILER_SUPPORTS_EXTERN_TEMPLATES 1
    #define FOUNDATION_COMPILER_SUPPORTS_NULLPTR 0
    #define FOUNDATION_COMPILER_SUPPORTS_STRONGLY_TYPED_ENUMS 1
    #define FOUNDATION_COMPILER_SUPPORTS_ALIGNMENT 0
    #define FOUNDATION_COMPILER_SUPPORTS_DELEGATING_CONSTRUCTORS 0
    #define FOUNDATION_COMPILER_SUPPORTS_INHERITING_CONSTRUCTORS 0
    #define FOUNDATION_COMPILER_SUPPORTS_UNRESTRICTED_UNIONS 0
  #elif (FOUNDATION_COMPILER_ICC >= 1110)
    #define FOUNDATION_COMPILER_SUPPORTS_RVALUES 0
    #define FOUNDATION_COMPILER_SUPPORTS_VARADIC_TEMPLATES 0
    #define FOUNDATION_COMPILER_SUPPORTS_INITIALIZER_LISTS 0
    #define FOUNDATION_COMPILER_SUPPORTS_STATIC_ASSERTIONS 1
    #define FOUNDATION_COMPILER_SUPPORTS_AUTO 0
    #define FOUNDATION_COMPILER_SUPPORTS_LAMBDAS_AND_CLOSURES 0
    #define FOUNDATION_COMPILER_SUPPORTS_DECLTYPE 0
    // #define FOUNDATION_COMPILER_SUPPORTS_RIGHT_ANGLE_BRACKETS 1
    #define FOUNDATION_COMPILER_SUPPORTS_DEFAULT_TEMPLATE_ARGUMENTS_FOR_FUNCTIONS 0
    #define FOUNDATION_COMPILER_SUPPORTS_ALIAS_TEMPLATES 0
    #define FOUNDATION_COMPILER_SUPPORTS_EXTERN_TEMPLATES 1
    #define FOUNDATION_COMPILER_SUPPORTS_NULLPTR 0
    #define FOUNDATION_COMPILER_SUPPORTS_STRONGLY_TYPED_ENUMS 1
    #define FOUNDATION_COMPILER_SUPPORTS_ALIGNMENT 0
    #define FOUNDATION_COMPILER_SUPPORTS_DELEGATING_CONSTRUCTORS 0
    #define FOUNDATION_COMPILER_SUPPORTS_INHERITING_CONSTRUCTORS 0
    #define FOUNDATION_COMPILER_SUPPORTS_UNRESTRICTED_UNIONS 0
  #endif
#endif

#endif // _FOUNDATION_DETECT_SUPPORTED_STANDARDS_H_
